"""add name_key to professor_ratings

Revision ID: 2b33cdb26e1b
Revises: 3830128a748b
Create Date: 2026-02-27 17:29:41.318443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b33cdb26e1b'
down_revision: Union[str, Sequence[str], None] = '3830128a748b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professor_ratings', sa.Column('name_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_professor_ratings_name_key'), 'professor_ratings', ['name_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professor_ratings_name_key'), table_name='professor_ratings')
    op.drop_column('professor_ratings', 'name_key')
    # ### end Alembic commands ###
