"""add professor_ratings table

Revision ID: 3830128a748b
Revises: d9ed2ea913f6
Create Date: 2026-02-26 20:54:54.778152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3830128a748b'
down_revision: Union[str, Sequence[str], None] = 'd9ed2ea913f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('catalog_number', sa.String(), nullable=False),
    sa.Column('num_ratings', sa.Integer(), nullable=True),
    sa.Column('avg_quality', sa.Float(), nullable=True),
    sa.Column('avg_difficulty', sa.Float(), nullable=True),
    sa.Column('would_take_again_pct', sa.Float(), nullable=True),
    sa.Column('attendance_mandatory', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professor_ratings_instructor_name'), 'professor_ratings', ['instructor_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professor_ratings_instructor_name'), table_name='professor_ratings')
    op.drop_table('professor_ratings')
    # ### end Alembic commands ###
