"""add name_key to sections

Revision ID: 9de6d85f01d8
Revises: 2b33cdb26e1b
Create Date: 2026-03-02 13:23:52.008879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de6d85f01d8'
down_revision: Union[str, Sequence[str], None] = '2b33cdb26e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('name_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_sections_name_key'), 'sections', ['name_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_name_key'), table_name='sections')
    op.drop_column('sections', 'name_key')
    # ### end Alembic commands ###
