"""initial tables

Revision ID: d9ed2ea913f6
Revises: 
Create Date: 2026-02-26 19:20:24.218503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ed2ea913f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('catalog_number', sa.String(), nullable=False),
    sa.Column('course_key', sa.String(), nullable=False),
    sa.Column('normalized_course_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_catalog_number'), 'courses', ['catalog_number'], unique=False)
    op.create_index(op.f('ix_courses_course_key'), 'courses', ['course_key'], unique=True)
    op.create_index(op.f('ix_courses_normalized_course_key'), 'courses', ['normalized_course_key'], unique=True)
    op.create_index(op.f('ix_courses_subject'), 'courses', ['subject'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('class_section', sa.String(), nullable=False),
    sa.Column('schedule_raw', sa.String(), nullable=True),
    sa.Column('instructor_name', sa.String(), nullable=True),
    sa.Column('days', sa.String(), nullable=True),
    sa.Column('start_min', sa.Integer(), nullable=True),
    sa.Column('end_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_course_id'), 'sections', ['course_id'], unique=False)
    op.create_index(op.f('ix_sections_days'), 'sections', ['days'], unique=False)
    op.create_index(op.f('ix_sections_end_min'), 'sections', ['end_min'], unique=False)
    op.create_index(op.f('ix_sections_start_min'), 'sections', ['start_min'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_start_min'), table_name='sections')
    op.drop_index(op.f('ix_sections_end_min'), table_name='sections')
    op.drop_index(op.f('ix_sections_days'), table_name='sections')
    op.drop_index(op.f('ix_sections_course_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_courses_subject'), table_name='courses')
    op.drop_index(op.f('ix_courses_normalized_course_key'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_key'), table_name='courses')
    op.drop_index(op.f('ix_courses_catalog_number'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
